// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using AppServiceOverview.Windows.FrcRank;
using Microsoft.Rest;

namespace AppServiceOverview.Windows.FrcRank
{
    public partial class Frcrankapi01 : ServiceClient<Frcrankapi01>, IFrcrankapi01
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private ITeams _teams;
        
        public virtual ITeams Teams
        {
            get { return this._teams; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Frcrankapi01 class.
        /// </summary>
        public Frcrankapi01()
            : base()
        {
            this._teams = new Teams(this);
            this._baseUri = new Uri("https://microsoft-apiappf6fa5484ea724b0085c8d603f47f8719.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the Frcrankapi01 class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Frcrankapi01(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._teams = new Teams(this);
            this._baseUri = new Uri("https://microsoft-apiappf6fa5484ea724b0085c8d603f47f8719.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the Frcrankapi01 class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Frcrankapi01(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._teams = new Teams(this);
            this._baseUri = new Uri("https://microsoft-apiappf6fa5484ea724b0085c8d603f47f8719.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the Frcrankapi01 class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Frcrankapi01(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the Frcrankapi01 class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Frcrankapi01(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the Frcrankapi01 class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public Frcrankapi01(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
