// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AppServiceOverview.Windows.FrcRank.Models;
using Microsoft.Rest;

namespace AppServiceOverview.Windows.FrcRank
{
    public partial interface ITeams
    {
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Team>> GetByIdWithOperationResponseAsync(int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='triggerState'>
        /// Required.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<Team>> GetRankUpdatedTriggerByTriggerstateAndIdWithOperationResponseAsync(string triggerState, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
