// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AppServiceOverview.Windows.FrcRank;
using AppServiceOverview.Windows.FrcRank.Models;
using Microsoft.Rest;

namespace AppServiceOverview.Windows.FrcRank
{
    public static partial class TeamsExtensions
    {
        /// <param name='operations'>
        /// Reference to the AppServiceOverview.Windows.FrcRank.ITeams.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static Team GetById(this ITeams operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ITeams)s).GetByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the AppServiceOverview.Windows.FrcRank.ITeams.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Team> GetByIdAsync(this ITeams operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<AppServiceOverview.Windows.FrcRank.Models.Team> result = await operations.GetByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the AppServiceOverview.Windows.FrcRank.ITeams.
        /// </param>
        /// <param name='triggerState'>
        /// Required.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static Team GetRankUpdatedTriggerByTriggerstateAndId(this ITeams operations, string triggerState, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ITeams)s).GetRankUpdatedTriggerByTriggerstateAndIdAsync(triggerState, id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the AppServiceOverview.Windows.FrcRank.ITeams.
        /// </param>
        /// <param name='triggerState'>
        /// Required.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Team> GetRankUpdatedTriggerByTriggerstateAndIdAsync(this ITeams operations, string triggerState, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<AppServiceOverview.Windows.FrcRank.Models.Team> result = await operations.GetRankUpdatedTriggerByTriggerstateAndIdWithOperationResponseAsync(triggerState, id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
