// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace AppServiceOverview.Windows.FrcRank.Models
{
    public partial class Team
    {
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private DateTimeOffset? _lastUpdated;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? LastUpdated
        {
            get { return this._lastUpdated; }
            set { this._lastUpdated = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private DateTimeOffset? _nextMatch;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? NextMatch
        {
            get { return this._nextMatch; }
            set { this._nextMatch = value; }
        }
        
        private int? _rank;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Rank
        {
            get { return this._rank; }
            set { this._rank = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Team class.
        /// </summary>
        public Team()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken lastUpdatedValue = inputObject["LastUpdated"];
                if (lastUpdatedValue != null && lastUpdatedValue.Type != JTokenType.Null)
                {
                    this.LastUpdated = ((DateTimeOffset)lastUpdatedValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken nextMatchValue = inputObject["NextMatch"];
                if (nextMatchValue != null && nextMatchValue.Type != JTokenType.Null)
                {
                    this.NextMatch = ((DateTimeOffset)nextMatchValue);
                }
                JToken rankValue = inputObject["Rank"];
                if (rankValue != null && rankValue.Type != JTokenType.Null)
                {
                    this.Rank = ((int)rankValue);
                }
            }
        }
    }
}
